//from http://de1.api.radio-browser.info/json/stations/search?countrycode=AT&hidebroken=true&order=votes&limit=10&reverse=true
export type stationsListInterface = {
    name:string,
    url_resolved: string,
    favicon: string,
    homepage:string,
    tags: string,
    countrycode: string,
    votes: number,
    codec: string,
    bitrate: number
}


export const stationsList:stationsListInterface[] = [
    {
        'name': 'Europa Plus',
        'url_resolved': 'http://ep256.hostingradio.ru:8052/europaplus256.mp3',
        'favicon': 'http://liveam.tv/img/2494.jpg',
        'homepage': 'http://www.europaplus.ru/',
        'tags': 'pop',
        'countrycode': 'RU',
        'votes': 12946,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'Вести ФМ (Vesti FM)',
        'url_resolved': 'http://icecast.vgtrk.cdnvideo.ru/vestifm_mp3_192kbps',
        'favicon': '',
        'homepage': 'http://radiovesti.ru/',
        'tags': 'news',
        'countrycode': 'RU',
        'votes': 11407,
        'codec': 'MP3',
        'bitrate': 192
    },
    {
        'name': 'Ретро FM',
        'url_resolved': 'http://retroserver.streamr.ru:8043/retro256.mp3',
        'favicon': 'http://retrofm.ru/favicon.ico',
        'homepage': 'http://retrofm.ru/',
        'tags': 'old',
        'countrycode': 'RU',
        'votes': 11109,
        'codec': 'MP3',
        'bitrate': 256
    },
    {
        'name': 'ROCK FM',
        'url_resolved': 'http://nashe1.hostingradio.ru/rock-128.mp3',
        'favicon': 'https://lh3.googleusercontent.com/D3taObR7tfyhwDFY40VS8DIVri7iif5RuzI9C-mXxRwF41vGZ_dO_n6MWM57P-mZczFC=w300',
        'homepage': 'http://www.rockfm.ru/',
        'tags': 'rock',
        'countrycode': 'RU',
        'votes': 11005,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'Шансон Радио',
        'url_resolved': 'http://chanson.hostingradio.ru:8041/chanson128.mp3',
        'favicon': 'https://www.radiobells.com/stations/chanson.jpg',
        'homepage': 'http://radioshanson.fm/',
        'tags': 'chanson',
        'countrycode': 'RU',
        'votes': 10966,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'дорожное радио (Dorognoe Radio)',
        'url_resolved': 'http://dorognoe.hostingradio.ru:8000/dorognoe',
        'favicon': 'https://dorognoe.ru/thumb/og_image_600x315/sharing_image/2016/ff/91/57cd63d58643c_sharind_dorognoe.jpg',
        'homepage': 'https://dorognoe.ru/',
        'tags': 'pop',
        'countrycode': 'RU',
        'votes': 10965,
        'codec': 'MP3',
        'bitrate': 64000
    },
    {
        'name': 'DFM RUSSIAN DANCE',
        'url_resolved': 'https://dfm-dfmrusdance.hostingradio.ru/dfmrusdance96.aacp?0.9987259013359274',
        'favicon': '',
        'homepage': 'https://dfm.ru/',
        'tags': 'pop',
        'countrycode': 'RU',
        'votes': 10825,
        'codec': 'AAC+',
        'bitrate': 96
    },
    {
        'name': 'DFM Дискач 90-х',
        'url_resolved': 'https://dfm-disc90.hostingradio.ru/disc9096.aacp',
        'favicon': '',
        'homepage': 'https://dfm.ru/',
        'tags': 'old',
        'countrycode': 'RU',
        'votes': 9739,
        'codec': 'AAC+',
        'bitrate': 96
    },
    {
        'name': '8bitFM',
        'url_resolved': 'http://8bit.fm:8000/live',
        'favicon': 'http://8bit.fm/favicon.ico',
        'homepage': 'http://8bit.fm/',
        'tags': 'electronic',
        'countrycode': 'RU',
        'votes': 8041,
        'codec': 'MP3',
        'bitrate': 192
    },
    {
        'name': 'Радио Русские Песни',
        'url_resolved': 'http://listen.rusongs.ru/ru-mp3-128',
        'favicon': 'http://rusongs.ru/images/logo_rusongs.png',
        'homepage': 'http://rusongs.ru/',
        'tags': 'pop',
        'countrycode': 'RU',
        'votes': 7893,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'Nashe Radio',
        'url_resolved': 'http://nashe1.hostingradio.ru/nashe-128.mp3',
        'favicon': 'http://static.radio.de/images/broadcasts/80/50/12551/c175.png',
        'homepage': 'http://www.nashe.ru/',
        'tags': 'pop',
        'countrycode': 'RU',
        'votes': 7619,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'Юмор FM (Humor FM)',
        'url_resolved': 'http://listen.vdfm.ru:8000/humor',
        'favicon': 'http://www.veseloeradio.ru/design/images/assets/img/icons/touch-icon-ipad.png',
        'homepage': 'http://www.veseloeradio.ru/',
        'tags': 'humor',
        'countrycode': 'RU',
        'votes': 6570,
        'codec': 'MP3',
        'bitrate': 256
    },
    {
        'name': 'Радио Маяк (Radio Mayak)',
        'url_resolved': 'http://icecast.vgtrk.cdnvideo.ru/mayakfm_mp3_192kbps',
        'favicon': '',
        'homepage': 'http://www.radiomayak.ru/',
        'tags': 'news',
        'countrycode': 'RU',
        'votes': 6439,
        'codec': 'MP3',
        'bitrate': 192
    },
    {
        'name': 'Ретро FM 70e',
        'url_resolved': 'http://retro70.hostingradio.ru:8025/retro70-128.mp3',
        'favicon': 'http://retrofm.ru/online/multiplayer/core/ext/logo_rfm_70.png?v=2',
        'homepage': 'http://retrofm.ru/',
        'tags': 'old',
        'countrycode': 'RU',
        'votes': 5934,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'Дорожное радио',
        'url_resolved': 'http://dorognoe.hostingradio.ru:8000/radio',
        'favicon': 'https://www.prfm.ru/logo/dorozhnoe-logo.png',
        'homepage': 'https://dorognoe.ru/?region=piter',
        'tags': 'pop',
        'countrycode': 'RU',
        'votes': 5315,
        'codec': 'MP3',
        'bitrate': 320000
    },
    {
        'name': 'Comedy Radio new link',
        'url_resolved': 'http://ic6.101.ru:8000/stream/air/aac/64/202',
        'favicon': 'https://comedy-radio.ru/design/images/logo/touch-icon-ipad.png',
        'homepage': 'https://comedy-radio.ru/',
        'tags': 'humor',
        'countrycode': 'RU',
        'votes': 5290,
        'codec': 'AAC+',
        'bitrate': 64
    },
    {
        'name': 'Радио «Комсомольская Правда» | КП Россия',
        'url_resolved': 'http://kpradio.hostingradio.ru:8000/russia.radiokp128.mp3',
        'favicon': '',
        'homepage': 'https://www.kp.ru/radio',
        'tags': 'news',
        'countrycode': 'RU',
        'votes': 4872,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'Дискотека СССР',
        'url_resolved': 'http://pub0302.101.ru:8000/stream/pro/aac/64/144?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpcCI6IjUuMTguMjQ4Ljk4IiwidXNlcmFnZW50IjoiTW96aWxsYVwvNS4wIChYMTE7IExpbnV4IHg4Nl82NDsgcnY6ODIuMCkgR2Vja29cLzIwMTAwMTAxIEZpcmVmb3hcLzgyLjAiLCJ1aWRfY2hhbm5lbCI6IjE0NCIsInR5cGVfY2hhbm5lbCI6ImNoYW5uZWwiLCJleHAiOjE2MDU5NjQ1MTZ9.Ln1wEJ8cHHzK_Ea6Zr8J8acdny0R9ShZ_KUKVf6TmQA',
        'favicon': 'https://cdn2.101.ru/vardata/modules/channel/image/c34932ae363a2b1386c0136d403a2274.png',
        'homepage': 'https://discoussr.101.ru/',
        'tags': 'old',
        'countrycode': 'RU',
        'votes': 4810,
        'codec': 'AAC+',
        'bitrate': 64
    },
    {
        'name': 'Ретро FM 80e',
        'url_resolved': 'https://hls-01-retro80.emgsound.ru/2/96/playlist.m3u8',
        'favicon': 'http://retrofm.ru/online/multiplayer/core/ext/logo_rfm_80.png?v=2',
        'homepage': 'http://retrofm.ru/',
        'tags': 'old',
        'countrycode': 'RU',
        'votes': 4396,
        'codec': 'UNKNOWN',
        'bitrate': 0
    },
    {
        'name': 'Radio Palitra 103.9 FM',
        'url_resolved': 'http://92.241.82.245:8000/live',
        'favicon': 'http://www.palitratv.ge/images/stories/palitratvlogo.png',
        'homepage': 'http://www.palitratv.ge/',
        'tags': 'pop',
        'countrycode': 'GE',
        'votes': 731,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'Tbilisi FM 93,5',
        'url_resolved': 'http://iis.ge:8000/radiotbilisi.mp3',
        'favicon': '',
        'homepage': 'http://tbilisifm.com/',
        'tags': 'news',
        'countrycode': 'GE',
        'votes': 577,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'Mutant Radio',
        'url_resolved': 'https://listen.radioking.com/radio/282820/stream/328621',
        'favicon': 'https://mutantradio.net/wp-content/uploads/2019/10/cropped-gravatar-180x180.jpg',
        'homepage': 'https://mutantradio.net/',
        'tags': 'electronic',
        'countrycode': 'GE',
        'votes': 510,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'რადიო "ძველი ქალაქი Старый город',
        'url_resolved': 'http://iis.ge:8000/radiodk.mp3',
        'favicon': 'http://www.radiodk.ge//images/temp/2016/07/07/1d06c40ed1f368b93c717a1601dc96c9.png',
        'homepage': 'http://www.radiodk.ge/',
        'tags': 'pop',
        'countrycode': 'GE',
        'votes': 495,
        'codec': 'MP3',
        'bitrate': 0
    },
    {
        'name': 'Energy NRJ Georgia',
        'url_resolved': 'http://shaincast.caster.fm:24734/listen.mp3?none',
        'favicon': '',
        'homepage': '',
        'tags': 'pop',
        'countrycode': 'GE',
        'votes': 465,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'Hereti FM',
        'url_resolved': 'http://iis.ge:8000/hereti.mp3',
        'favicon': 'https://cdn.onlineradiobox.com/img/logo/6/43916.png',
        'homepage': 'http://www.heretifm.com/',
        'tags': 'pop',
        'countrycode': 'GE',
        'votes': 415,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'Radio Amra',
        'url_resolved': 'https://streamer.radio.co/s34b5469e0/listen',
        'favicon': '',
        'homepage': '',
        'tags': 'old',
        'countrycode': 'GE',
        'votes': 323,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'Marneuli FM',
        'url_resolved': 'http://stream.it-solutions.ge:8000/mp3-radiomarneulifm',
        'favicon': 'https://www.marneulifm.ge//images/temp/2017/06/14/91d0264419f7bc69b396106ffac4345e.png',
        'homepage': 'https://www.marneulifm.ge/',
        'tags': 'pop',
        'countrycode': 'GE',
        'votes': 298,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'Радио SK',
        'url_resolved': 'http://iis.ge:8000/sk.mp3',
        'favicon': 'http://sknews.ge//favicon.ico',
        'homepage': 'http://sknews.ge/',
        'tags': 'pop',
        'countrycode': 'GE',
        'votes': 281,
        'codec': 'MP3',
        'bitrate': 152
    },
    {
        'name': 'Radio NOR',
        'url_resolved': 'http://iis.ge:8000/nor.mp3',
        'favicon': 'http://nor.ge/favicon.ico',
        'homepage': 'http://nor.ge/',
        'tags': 'news',
        'countrycode': 'GE',
        'votes': 203,
        'codec': 'MP3',
        'bitrate': 185
    },
    {
        'name': 'Radio Paradise (320k)',
        'url_resolved': 'http://stream-uk1.radioparadise.com/aac-320',
        'favicon': 'https://www.radioparadise.com/favicon.ico',
        'homepage': 'https://www.radioparadise.com/',
        'tags': 'old',
        'countrycode': 'US',
        'votes': 51985,
        'codec': 'AAC',
        'bitrate': 320
    },
    {
        'name': 'Classic Vinyl HD',
        'url_resolved': 'https://walmradio.com:8443/classic',
        'favicon': 'https://walmradio.com:8443/WALM_record_512x512.png',
        'homepage': 'https://walmradio.com/',
        'tags': 'old',
        'countrycode': 'US',
        'votes': 32092,
        'codec': 'MP3',
        'bitrate': 320
    },
    {
        'name': 'Adroit Jazz Underground',
        'url_resolved': 'https://walmradio.com:8443/jazz',
        'favicon': '',
        'homepage': 'https://walmradio.com/',
        'tags': 'old',
        'countrycode': 'US',
        'votes': 28622,
        'codec': 'MP3',
        'bitrate': 320
    },
    {
        'name': 'WALM',
        'url_resolved': 'https://walmradio.com:8443/walm',
        'favicon': 'https://walmradio.com:8443/WALM_record_512x512.png',
        'homepage': 'https://walmradio.com/',
        'tags': 'old',
        'countrycode': 'US',
        'votes': 26387,
        'codec': 'MP3',
        'bitrate': 320
    },
    {
        'name': 'Deep House Lounge',
        'url_resolved': 'http://198.15.94.34:8006/stream',
        'favicon': 'https://secureimg.stitcher.com/feedimagesplain328/42300.jpg',
        'homepage': 'http://www.deephouselounge.com/',
        'tags': 'deep house,disco,electronica,funky,house,jazzy,lounge,philadelphia,techno',
        'countrycode': 'US',
        'votes': 19517,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'SomaFM Groove Salad',
        'url_resolved': 'http://ice3.somafm.com/groovesalad-128-mp3',
        'favicon': '',
        'homepage': 'http://somafm.com/groovesalad',
        'tags': 'electronic',
        'countrycode': 'US',
        'votes': 19497,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'Rockabilly-radio.net',
        'url_resolved': 'http://lin3.ash.fast-serv.com:6026/stream_96',
        'favicon': 'http://www.rockabilly-radio.net/images/8.png',
        'homepage': 'http://rockabilly-radio.net/',
        'tags': 'pop',
        'countrycode': 'US',
        'votes': 14606,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': '101 SMOOTH JAZZ',
        'url_resolved': 'http://jking.cdnstream1.com/b22139_128mp3',
        'favicon': 'http://101smoothjazz.com/favicon.ico',
        'homepage': 'http://101smoothjazz.com/',
        'tags': 'old',
        'countrycode': 'US',
        'votes': 12125,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'Beatles Radio',
        'url_resolved': 'http://www.beatlesradio.com:8000/stream/1/',
        'favicon': '',
        'homepage': 'http://www.beatlesradio.com/',
        'tags': 'old',
        'countrycode': 'US',
        'votes': 10966,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'ORF Hitradio Ö3',
        'url_resolved': 'http://orf-live.ors-shoutcast.at/oe3-q1a',
        'favicon': 'http://static.radio.net/images/broadcasts/47/5f/4511/c175.png',
        'homepage': 'http://oe3.orf.at/',
        'tags': 'pop',
        'countrycode': 'AT',
        'votes': 2317,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'Chill Out Zone',
        'url_resolved': 'http://air.chillout.zone:8000/radio',
        'favicon': 'http://static.tumblr.com/5f6637bbc70ea25ad9381fb8a45dd96b/iggknak/AAFnk62e5/tumblr_static_3ofi0bchjmskgwswc0g8go4cw.jpg',
        'homepage': 'http://chillout.zone/',
        'tags': 'electronic',
        'countrycode': 'AT',
        'votes': 1588,
        'codec': 'MP3',
        'bitrate': 320
    },
    {
        'name': 'ORF Ö1',
        'url_resolved': 'https://orf-live.ors-shoutcast.at/oe1-q2a',
        'favicon': 'http://oe1.orf.at/static/img/logo_oe1.png',
        'homepage': 'https://oe1.orf.at/player/live',
        'tags': 'news',
        'countrycode': 'AT',
        'votes': 1377,
        'codec': 'MP3',
        'bitrate': 192
    },
    {
        'name': 'radio FM4 (192 kbps)',
        'url_resolved': 'https://orf-live.ors-shoutcast.at/fm4-q2a',
        'favicon': 'https://tubestatic.orf.at/mojo/1_3/storyserver//tube/fm4/images/fm4.logo.svg',
        'homepage': 'https://fm4.orf.at/',
        'tags': 'pop',
        'countrycode': 'AT',
        'votes': 998,
        'codec': 'MP3',
        'bitrate': 192
    },
    {
        'name': 'Austrian Rock Radio',
        'url_resolved': 'http://live.antenne.at/arr',
        'favicon': '',
        'homepage': 'http://www.austrianrockradio.at/',
        'tags': 'pop',
        'countrycode': 'AT',
        'votes': 947,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'KroneHit Digital',
        'url_resolved': 'http://onair-ha1.krone.at/kronehit1058.mp3',
        'favicon': 'http://www.kronehit.at/favicon.ico',
        'homepage': 'http://www.kronehit.at/',
        'tags': 'electronic',
        'countrycode': 'AT',
        'votes': 848,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'Antenne Steiermark',
        'url_resolved': 'http://live.antenne.at/as',
        'favicon': 'https://upload.wikimedia.org/wikipedia/commons/6/63/Antenne_Logo.svg',
        'homepage': 'http://www.antenne.at/',
        'tags': 'electronic',
        'countrycode': 'AT',
        'votes': 699,
        'codec': 'MP3',
        'bitrate': 128
    },
    {
        'name': 'Radio OE3 neu',
        'url_resolved': 'http://orf-live.ors-shoutcast.at/oe3-q2a',
        'favicon': 'https://files.orf.at/vietnam2/files/oe3/201946/oe3_logo_715017.png',
        'homepage': 'https://radiothek.orf.at/oe3/live',
        'tags': 'pop',
        'countrycode': 'AT',
        'votes': 617,
        'codec': 'MP3',
        'bitrate': 192
    },
    {
        'name': 'Chill Out Zone Plus - Lossless/FLAC',
        'url_resolved': 'http://chillout.zone/chillout_plus',
        'favicon': 'https://chillout.zone//tpl/icons/ms-icon-144x144.png',
        'homepage': 'https://chillout.zone/',
        'tags': 'electronic',
        'countrycode': 'AT',
        'votes': 567,
        'codec': 'OGG',
        'bitrate': 0
    }]